import Head from "next/head";

import Post from "../components/Post";
import PostForm from "../components/PostForm";
import Bio from "../components/Bio"
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio 
          headshot="https://avatars.githubusercontent.com/u/34556282?s=400&u=143676d757968aeb5e5135326963bb0d8265bec6&v=4"
          name="Ali Koçman"
          tagline="Helping others to learn by doing!"
          role="Developer Advocate @ Applitools"
        />

        <ul className={styles.posts}>
          <li>
            <Post
              content="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
              date="3/2/2021"
            />
          </li>
          <li>
            <Post
              content="Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
              date="6/9/2021"
            />
          </li>
          <li>
            <Post
              content="When an unknown printer took a galley of type and scrambled it to make a type specimen book."
              date="8/9/2021"
            />
          </li>
          <li>
            <Post
              content="It has survived not only five centuries."
              date="10/5/2021"
            />
          </li>
          <li>
            <Post content="Remaining essentially unchanged." date="7/12/2021" />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
