import { useState, useEffect } from "react";
import Head from "next/head";

import { useAuth } from '../hooks/useAuth'
import { getAllPostst, createPost } from '../lib/posts'
 
import Post from "../components/Post";
import PostForm from "../components/PostForm";
import Bio from "../components/Bio"
import styles from "../styles/Home.module.scss";

export default function Home({ posts: defaultPosts }) {

  const [posts, updatePosts] = useState(defaultPosts);

  const postsSorted = posts.sort(function(a, b) {
    return new Date(b.date) - new Date(a.date);
  })

  async function handleOnSubmit(data, e) {
    e.preventDefault();

    await createPost(data);

    const posts = await getAllPostst();
    updatePosts(posts)
  }

  const { user, logIn, logOut } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { !user && (
        <p>
          <button onClick={logIn}>Log In</button>
        </p>
      ) }

      { user && (
        <p>
          <button onClick={logOut}>Log Out</button>
        </p>
      ) }

      <main className={styles.main}>
        <Bio 
          headshot="https://avatars.githubusercontent.com/u/34556282?s=400&u=143676d757968aeb5e5135326963bb0d8265bec6&v=4"
          name="Ali Koçman"
          tagline="Helping others to learn by doing!"
          role="Developer Advocate @ Applitools"
        />

        <ul className={styles.posts}>
          {postsSorted.map(post => {
            const { content, id, date } = post;
            return (
              <li key={id}>
                <Post
                  content={content}
                  date={new Intl.DateTimeFormat('en-US', {
                    dateStyle: 'short', 
                    timeStyle: 'short'
                  }).format(new Date(date))}
                />
              </li>
            )
          })}
        </ul>

        { user && (
          <PostForm onSubmit={handleOnSubmit} />
        ) }
        
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // const posts = await getAllPostst();

  return {
    props: {
      posts
    }
  }
}